// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQPYSZ1lHsOzfvPzZTvpAsOwa2Ubs66w',
    appId: '1:243164581379:web:7eafe70e7b26d1ca4bc836',
    messagingSenderId: '243164581379',
    projectId: 'social-app-48b88',
    authDomain: 'social-app-48b88.firebaseapp.com',
    storageBucket: 'social-app-48b88.appspot.com',
    measurementId: 'G-6QR8FM7B9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcCN7H_W9E_W3k1QE3JVhJAwqU18PidkE',
    appId: '1:243164581379:android:342eebe244ecdabc4bc836',
    messagingSenderId: '243164581379',
    projectId: 'social-app-48b88',
    storageBucket: 'social-app-48b88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZXyJMzbhLt0CTCrifkxFc16xVW1AQMps',
    appId: '1:243164581379:ios:b26251abe11883bd4bc836',
    messagingSenderId: '243164581379',
    projectId: 'social-app-48b88',
    storageBucket: 'social-app-48b88.appspot.com',
    androidClientId: '243164581379-dr08dve9nj3flsf45sg36ug4eogpprq6.apps.googleusercontent.com',
    iosClientId: '243164581379-plbd46kcubmnnchccnanfj4e44695pp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.calendar',
  );
}
